version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: firstTradeUnion
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
